"""apiz — Official Python SDK for the apiz.ai AI generation platform."""

from __future__ import annotations

from ._errors import (
    ApizAuthenticationError,
    ApizConnectionError,
    ApizError,
    ApizInsufficientBalanceError,
    ApizNotFoundError,
    ApizPermissionDeniedError,
    ApizRateLimitError,
    ApizServerError,
    ApizTimeoutError,
    ApizValidationError,
    error_from_status,
)
from ._resources.captioning import parse_align_result
from ._types import (
    AlignMode,
    AlignParams,
    AlignPunctMode,
    AlignResult,
    AlignUtterance,
    AlignWord,
    BalanceResponse,
    Channel,
    CheckinResponse,
    GenerateResult,
    ModelCapability,
    ModelCategory,
    ModelDetail,
    ModelDocs,
    ModelSummary,
    PackageItem,
    ParseVideoResponse,
    PaymentResponse,
    SkillDetail,
    SkillSummary,
    SpeakModel,
    SyncImageResponse,
    SyncVideoResponse,
    SynthesizeParams,
    SynthesizeResponse,
    TaskCreateParams,
    TaskCreateResponse,
    TaskQueryResponse,
    TaskStatus,
    TransferUrlResponse,
    TransferUrlType,
    VoiceItem,
    VoiceListResponse,
)
from .client import Apiz, AsyncApiz

__version__ = "0.1.0"

__all__ = [
    # Clients
    "AlignMode",
    "AlignParams",
    "AlignPunctMode",
    "AlignResult",
    "AlignUtterance",
    "AlignWord",
    "Apiz",
    "ApizAuthenticationError",
    "ApizConnectionError",
    # Errors
    "ApizError",
    "ApizInsufficientBalanceError",
    "ApizNotFoundError",
    "ApizPermissionDeniedError",
    "ApizRateLimitError",
    "ApizServerError",
    "ApizTimeoutError",
    "ApizValidationError",
    "AsyncApiz",
    # Types
    "BalanceResponse",
    "Channel",
    "CheckinResponse",
    "GenerateResult",
    "ModelCapability",
    "ModelCategory",
    "ModelDetail",
    "ModelDocs",
    "ModelSummary",
    "PackageItem",
    "ParseVideoResponse",
    "PaymentResponse",
    "SkillDetail",
    "SkillSummary",
    "SpeakModel",
    "SyncImageResponse",
    "SyncVideoResponse",
    "SynthesizeParams",
    "SynthesizeResponse",
    "TaskCreateParams",
    "TaskCreateResponse",
    "TaskQueryResponse",
    "TaskStatus",
    "TransferUrlResponse",
    "TransferUrlType",
    "VoiceItem",
    "VoiceListResponse",
    # Meta
    "__version__",
    "error_from_status",
    "parse_align_result",
]
